# Generated by Django 5.2 on 2025-04-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=100)),
                ('read_key', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
            ],
        ),
    ]
