# Generated by Django 5.2 on 2025-04-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='channel_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='read_key',
            field=models.CharField(max_length=50),
        ),
    ]
